### ISSUE TITLE
VTT demo font documentation 

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/how-to-hint-variable-fonts#14]
Is the following text in the demo font readme

> Edits and Fine Tuning Ascii glyph set only, edited and fine tuned. Code comments added to the VTTTalk for
> 
> Capitals glyphs: HAMBURGEFONTSV Lowercase glyphs: hamburgerfontsiv
> 
> Accents Accents have hinting and fine tuning
> 
> Hinted Accent glyphs (Gid 67 / grave / Uni 0x60), (Gid 118/ acute / Uni 0xb4), (Gid 330 / circumflex / Uni 0x2c6), (Gid 331 / caron / Uni 0x2c7), (Gid 332 / macron / Uni 0x2c9), (Gid 333 / breve / Uni 0x2d8), (Gid 334 / dotaccent / Uni 0x2d9), (Gid 335 / ring / Uni 0x2da), (Gid 336 / ogonek / Uni 0x2db), (Gid 337 / tilde / Uni 0x2dc), (Gid 338 / hungarumlaut / Uni 0x2dd)
> 
> Composite glyphs with accent positioning code added
> 
> (GID 139 0xc9 Eacute (with comments), (GID 140 0xca Ecircumflex), (GID 163 0xe1 aacute), (GID 164 0xe2 acircumflex), (GID 165 0xe3 atilde), (GID 175 0xed iacute), (GID 177 0xef idieresis)

meant to be formatted as lists like below?

---

Edits and Fine Tuning Ascii glyph set only, edited and fine tuned. Code comments added to the VTTTalk for:

- Capitals glyphs: HAMBURGEFONTSV Lowercase glyphs: hamburgerfontsiv
- Accents Accents have hinting and fine tuning
- Hinted Accent glyphs (Gid 67 / grave / Uni 0x60), (Gid 118/ acute / Uni 0xb4), (Gid 330 / circumflex / Uni 0x2c6), (Gid 331 / caron / Uni 0x2c7), (Gid 332 / macron / Uni 0x2c9), (Gid 333 / breve / Uni 0x2d8), (Gid 334 / dotaccent / Uni 0x2d9), (Gid 335 / ring / Uni 0x2da), (Gid 336 / ogonek / Uni 0x2db), (Gid 337 / tilde / Uni 0x2dc), (Gid 338 / hungarumlaut / Uni 0x2dd)

Composite glyphs with accent positioning code added:

- (GID 139 0xc9 Eacute (with comments), (GID 140 0xca Ecircumflex), (GID 163 0xe1 aacute), (GID 164 0xe2 acircumflex), (GID 165 0xe3 atilde), (GID 175 0xed iacute), (GID 177 0xef idieresis)

---

Markdown syntax for the list format above:

```markdown
Edits and Fine Tuning Ascii glyph set only, edited and fine tuned. Code comments added to the VTTTalk for:

- Capitals glyphs: HAMBURGEFONTSV Lowercase glyphs: hamburgerfontsiv
- Accents Accents have hinting and fine tuning
- Hinted Accent glyphs (Gid 67 / grave / Uni 0x60), (Gid 118/ acute / Uni 0xb4), (Gid 330 / circumflex / Uni 0x2c6), (Gid 331 / caron / Uni 0x2c7), (Gid 332 / macron / Uni 0x2c9), (Gid 333 / breve / Uni 0x2d8), (Gid 334 / dotaccent / Uni 0x2d9), (Gid 335 / ring / Uni 0x2da), (Gid 336 / ogonek / Uni 0x2db), (Gid 337 / tilde / Uni 0x2dc), (Gid 338 / hungarumlaut / Uni 0x2dd)

Composite glyphs with accent positioning code added:

- (GID 139 0xc9 Eacute (with comments), (GID 140 0xca Ecircumflex), (GID 163 0xe1 aacute), (GID 164 0xe2 acircumflex), (GID 165 0xe3 atilde), (GID 175 0xed iacute), (GID 177 0xef idieresis)
```

**Comment by mikedug** [comment]
thanks Chris, I will update that.

**Comment by mikedug** [comment]
done
