### ISSUE TITLE
Saving VTT windows arrangement in fonts

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/how-to-hint-variable-fonts#15]
The root README.md doc states:

> On opening a Variation Font, you can arrange the Windows in VTT to suit your own workflow. Make any edit, and save (ctrl + s). This will save the VTT preferences. The next time a font file is opened in VTT you will see the same window configuration.

I opened the OpenSans demo font in VTT and adjusted the default window arrangement to display Top left: VTT Talk, Bottom left: Glyph program, Middle: main editor window, Right: Variation view window.

I tried `Ctrl-s` as stated in the docs and it didn't appear to save the windows configuration.  I can use the "Save as..." menu item to overwrite the file / write a new file with these settings.

**Comment by mikedug** [comment]
The save state behaviour for Window layout, has never been documented properly. I always make some random edit, in VTT Talk for the default glyph, then delete, and save. I will investigate, edit and update the text, when I know a reliable solution to this.

**Comment by mikedug** [comment]
Added some more explicit instruction, at the beginning of the VTT Design space setup section, for saving window configuration.
