### ISSUE TITLE
"Default" dpi setting / resolution review approach for new projects

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/how-to-hint-variable-fonts#16]
Re: README text:

> pt / ppem Currently selected point/ppem size reflecting the selected resolution (The resolution to display the text string and waterfall run in the main window can be changed (Display > Resolution > choose desired resolution). This is useful for proofing at both lower and high resolutions) Choose the size to view in the Main window, Display > Size > ..., or click on a size from the text ramp at the bottom of the Main Window. Use up and down arrows to change the point size, or ctrl + equals, and enter the desired size.

Do you have recommendations for a good resolution starting point in new projects?  The OpenSans demo font opens in 72dpi.  The visuals in the early part of the README doc are displayed at 96dpi.  As you approach a new project, do you tend to set the dpi at a certain value while you hint and then modify the resolution as you review work in progress or as a final pass review for refinements after the hinting edits are complete across the glyph set?

**Comment by mikedug** [comment]
I will update the doc to include a good recommendation, which would be to set the resolution to 72dpi. This allows the hinter to view and proof all sizes. I switch between different resolutions, as I progress in the hinting, to test and proof, but normally revert back to 72.

**Comment by mikedug** [comment]
Added 'Note on setting the resolution' while hinting to 72dpi, it the VTT Design space setup section.

**Comment by chrissimpkins** [comment]
Thank you!
