### ISSUE TITLE
Useful VTT keyboard shortcuts table

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/how-to-hint-variable-fonts#17]
There are a number of good shortcut nuggets embedded in the setup documentation text. It might be useful to include a table of your most commonly used keyboard shortcuts somewhere in this section.  If this is included under a linkable header it would serve as a good browser bookmark reference to these docs.

**Comment by mikedug** [comment]
Broke out the, most used VTT shortcuts, into a linkable header, after the VTT Design Space setup section

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/how-to-vtt#useful-keyboard-shortcuts

Looks great. Thanks Mike!
