### ISSUE TITLE
Set "Syntax coloring" in demo font

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/how-to-hint-variable-fonts#18]
Setting `Tools > Options > Settings > Syntax coloring` in the demo font sets the VTT talk comment annotations in a different color which makes it easier to distinguish documentation from the VTT source.  I find this easier to read.  It might be useful to save the demo font with this setting.

**Comment by mikedug** [comment]
Preferences set, to open the Demo font with Syntax coloring for code comments

**Comment by chrissimpkins** [comment]
Thank you!
