### ISSUE TITLE
Old paper on hinting very narrow type

### ISSUE THREAD

**Issue by davelab6** [googlefonts/how-to-hint-variable-fonts#25]
I wonder if https://core.ac.uk/download/pdf/147925121.pdf is relevant to hinting width axes variable fonts. I didn't read it closely. Maybe irrelevant :)

**Comment by mikedug** [comment]
hi Dave, not relevant for Variable font hinting. The techniques, such as described, wont help at all for stem sharpening for any font rendered with Subpixel-Positioning. 

For any one off static environment, that uses bi-level rendering or greyscale, but not subpixel-positioning, there are tried and trusted methods of hinting than can help to keep stems sharp, maintain symmetry and keep spacing consistent. Nina, for example, (Verdana Narrow) was hinted to look perfect at smaller sizes in bi-level. It is harder to combine greyscale with hinting, but if deltas can be used, good results can be achieved.
