### ISSUE TITLE
VTT Variable font workflow process

### ISSUE THREAD

**Issue by mikedug** [googlefonts/how-to-hint-variable-fonts#3]
This will be the main longer section, covering everything involved in the process of autohinting and fine tuning a Variable font, including expert tips and tricks. Topics will include:

- [x] Section Interspersed with Key concepts of hinting, covering from the top level of what we are trying to achieve (e.g. maintain stem width) to how we do it as an VTT user (set points and links in the UI) to how that is represented in inside VTT (in high level VTT Talk code) to how that is represented in the font (in low level TT instructions code in TT tables).
- [x] Original outline design recommendation for best hinting results.
- [x] How to Run the Autohinter 
- [x] Provide a short description of CVT, PreProgram and Font Program, VTT Talk and Glyph program. (Quote and link out to existing table documentation)
- [x] xml import-export editing recommendations (describe RESYDIST TO SHIFT replace, and why)
- [x] RES commands (Resolution Environment Specific) explanation
- [x] Hinting of control Characters including, (HAMBQRGERFONTVS upper and lowercase / plus code explanations and graphics / gifs including, how to use the commonly used UI tools for hinting.
- [x] Expert tips and tricks for fine tuning Autohinter results, covering typical editing scenarios. Common fixes, including Interpolations, removing autohinter outlier code, and how to recognise it. Ensuring efficient code / Proofing and checking code, visually, & editing VTT Talk
- [x] Controlling overshoot / undershoots and using CVT Inheritance
- [x] CVT table settings and using global cvt deltas to adjust vertical proportions / heights
- [x] CVAR editing
- [x] Detailed accent hinting and positioning description + graphics to ensure clear and consistent clear on-screen display.
- [x] Co-ordination of Roman and Italic VF fonts for consistent display.
- [x] Variable Font Proofing (including screen shot graphics)
- [x] GASP table editing description and editing 
- [x] VTT Workarounds / trouble shooting
- [x] Calculate MAXP, Saving and shipping

**Comment by mikedug** [comment]
hi @chrissimpkins 

let me know if you would like to chat before our scheduled meeting next week? 

I am preparing to get going on the main section of the Document, the workflow process of Hinting. You mentioned you use animated gifs in markdown files for some documentation? do you have a pointer to an example of using an animated gif? I have been using Snagit for Windows, which lets you create great animated gifs of short processes in VTT for example. Ideally I want something that can be used with a play/pause effect, not a looping gif, so I would like to figure out the best way to get this done.

**Comment by chrissimpkins** [comment]
> let me know if you would like to chat before our scheduled meeting next week?

This sounds great Mike.  I scheduled time tomorrow. Please let me know if that time works for you.

**Comment by chrissimpkins** [comment]
> do you have a pointer to an example of using an animated gif? I have been using Snagit for Windows, which lets you create great animated gifs of short processes in VTT for example.

Snagit works very well.  I use it on macOS.  Here is an example below

![examplegif](https://user-images.githubusercontent.com/4249591/127331643-50cecd2d-da17-4a19-b70e-c31121cfa30a.gif)

and the Markdown to display it:

```markdown
![examplegif](https://user-images.githubusercontent.com/4249591/127331643-50cecd2d-da17-4a19-b70e-c31121cfa30a.gif)
```

The syntax is:

```
![ANY NAME](URL to gif image file)
```

You should be able to use a relative file path in place of the URL if the image is checked in with git and pushed to the remote repository.

I am not aware of an approach to create start/stop interactions with gif animations.  I believe that they may only support one loop, (maybe a set number of loops?), and endless loops.

**Comment by mikedug** [comment]
thanks for the information on gifs Chris. That time is fine, I accepted the meeting, chat to you tomorrow.

**Comment by mikedug** [comment]
Section completed
